### ISSUE TITLE
bbbnnnnnnjjjjjb

### ISSUE THREAD

**Issue by GBeushausen** [Haehnchen/idea-php-symfony2-plugin#1947]

**Comment by Haehnchen** [comment]
> Is this some sort of malware?
This is THE most annoying plugin in PHPStorm. In every new project it asks to get activated though i almost never use Symfony. And now it even continuously opens a nag screen for me to buy a license?

Thank you for your motivating feedback. Its the best i got since ~10 years of developing this malware. :1st_place_medal: :-1: 

> i almost never use Symfony

so your solution is: remove "THE most annoying plugin"
