### ISSUE TITLE
Plugin not recognizing localized routes

### ISSUE THREAD

**Issue by tjveldhuizen** [Haehnchen/idea-php-symfony2-plugin#2247]
The plugin seems to have problems handling localized routes. In this example, the route name in all three of the generated URL's is valid (and working in my application), but only links to a specific locale are found by the plugin.

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/779998/a53f2c71-464c-4a6f-8cf1-fd3fc13b2cc5)

**Comment by damienalexandre** [comment]
I can confirm this issue.

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/225704/77d370d0-d942-4ad5-8288-0f1c573f7966)

I suspect this is due to the way Symfony is storing those routes inside `/var/cache/dev/url_generating_routes.php`:

```php
[ // ...
    'profile_plan.en' => [[], [
        '_controller' => 'App\\Controller\\ProfileController::plan', 
        '_locale' => 'en', 
        '_canonical_route' => 'profile_plan'
    ], [], [['text', '/account/plan']], [], [], []],
    'profile_plan.fr' => [[], [
        '_controller' => 'App\\Controller\\ProfileController::plan', 
        '_locale' => 'fr', 
        '_canonical_route' => 'profile_plan'
    ], [], [['text', '/fr/account/plan']], [], [], []],
```

I think the plugin should look at the **_canonical_route** option. When it's set, it means this route is a translation of a base route.

**Comment by tjveldhuizen** [comment]
Indeed! Great!
