### ISSUE TITLE
Missing Template and Weak Route in PHPStorm 9

### ISSUE THREAD

**Issue by bennyt2** [Haehnchen/idea-php-symfony2-plugin#588]
When I hover over the template name in a `render` function, a "Missing template" warning appears. 
![missing template](https://cloud.githubusercontent.com/assets/5905154/10092957/68f32600-631a-11e5-81df-ab999c39d2d2.png)

However, the template does exist. It may also help to note that the `meet_index` route name is defined as a weak route.
![weak route](https://cloud.githubusercontent.com/assets/5905154/10092956/68f16130-631a-11e5-9aa1-14ebdf0b74c8.png)

I've cleared caches and ensured that appDevDebugProjectContainer.php is up to date. Any thoughts about what this could be?

PHPStorm 9
Plugin version: 0.11.98
Symfony 2.7 full stack

**Comment by enachesilviu** [comment]
The warning goes away if you rename the method from "indexAction" to "index". Routing would still work thanks to Route annotation but this is not a good practice since this breaks the controller naming pattern here: http://symfony.com/doc/current/book/routing.html#controller-naming-pattern

I, too, wish for a fix to this.

**Comment by Haehnchen** [comment]
- annotation routes also supported now.
 - missing template: you have an upper / lower; see Bundle vs. Template name
