### ISSUE TITLE
"Missing asset" warning on @ notation

### ISSUE THREAD

**Issue by xDaizu** [Haehnchen/idea-php-symfony2-plugin#758]
It throws a "Missing asset" warning in lines like:

`<link href="{{ asset('@PersonBundle/Resources/public/css/people-list.css') }}" rel="stylesheet" type="text/css"/>`

even though the file exists (checked thrice), both the original in `src/License/PersonBundle/Resources/public/css/people-list.scss` and its copy to `web/bundles/licenseperson/css/people-list.css`

**Comment by stof** [comment]
The ``asset()`` function just prepends the base path and applies the version. It does not turn ``@PersonBundle/Resources/public/`` into ``bundles/licenseperson/`` (unless you implemented some special code to handle it, but then the plugin will not know about this special feature)

So this warning is totally expected.

**Comment by xDaizu** [comment]
>  It does not turn @PersonBundle/Resources/public/ into bundles/licenseperson/

I understand that, but shouldn't it find the `src/License/PersonBundle/Resources/public/css/people-list.css` file?

**Comment by stof** [comment]
@xDaizu AFAIK, it never worked by default in Symfony.

**Comment by Haehnchen** [comment]
vice versa is the only option. `bundles/foo/` => `@FooBundle/...`, all others are third party implementations

**Comment by stof** [comment]
@Haehnchen I don't understand what you mean. ``asset()`` does not perform any path transformation other than applying the versionning and prepending the appropriate base path (in case you app is not deployed at the root of the host).
It does not have any special handling for ``bundles/foo`` (referencing assets with ``bundles/foo/...`` works because assets actually exist at that path after running ``assets:install`` to create the necessary symlinks)

**Comment by Haehnchen** [comment]
simply i want to rebuild the symlink behavior of `assets:install`. i often seeing projects inside VMs that dont have the links locally.

`bundles/app/css/*` navigates to `../AppBundle/Resources/public/css/*`

**Comment by Haehnchen** [comment]
closed. not a plugin feature, navigation with #815
